name: Deploy main branch
on:
  push:
    branches:
      - main
  # or manually
  workflow_dispatch:
    
# Required for secrets.GITHUB_TOKEN
permissions:
  packages: write
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Push to Github Container Repository
      uses: Clipr-Group/ghcr-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        platforms: linux/amd64,linux/arm64